### ISSUE TITLE
Compilation Error due to missing `Gaudi.xenv`

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4FWCore#1]
Using Gaudi v32r2, the build fails with the following error:
```
[ 20%] [32mBuilding CXX object FWCore/CMakeFiles/FWCore.dir/src/PodioDataSvc.cpp.o[0m
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_96c_LS/x86_64-centos7-gcc8-opt/bin/xenv", line 11, in <module>
    load_entry_point('xenv==1.0.0', 'console_scripts', 'xenv')()
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_96c_LS/x86_64-centos7-gcc8-opt/lib/python2.7/site-packages/xenv/__init__.py", line 369, in main
    Script().main()
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_96c_LS/x86_64-centos7-gcc8-opt/lib/python2.7/site-packages/xenv/__init__.py", line 361, in main
    self._makeEnv()
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_96c_LS/x86_64-centos7-gcc8-opt/lib/python2.7/site-packages/xenv/__init__.py", line 272, in _makeEnv
    getattr(control, action)(*args)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_96c_LS/x86_64-centos7-gcc8-opt/lib/python2.7/site-packages/xenv/Control.py", line 307, in loadXML
    self.actions[action](*args)  # pylint: disable=W0142
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_96c_LS/x86_64-centos7-gcc8-opt/lib/python2.7/site-packages/xenv/Control.py", line 59, in <lambda>
    'include'] = lambda n, c, h: self.loadXML(self._locate(n, c, h))
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_96c_LS/x86_64-centos7-gcc8-opt/lib/python2.7/site-packages/xenv/Control.py", line 128, in _locate
    raise OSError(ENOENT, 'cannot find file in %r' % sp, filename)
OSError: [Errno 2] cannot find file in ['.', '/cvmfs/sft.cern.ch/lcg/views/LCG_96c_LS/x86_64-centos7-gcc8-opt/cmake', '/workspace/build/config/']: 'Gaudi.xenv'
```
This problem does not appear with Gaudi v29r0.

**Comment by vvolkl** [comment]
There is a workaround for this issue: explicitly setting the environment variable `Gaudi_DIR` to the LCG installation.
