### ISSUE TITLE
Merge `k4DataSvc` and `PodioDataSvc`

### ISSUE THREAD

**Issue by tmadlener** [key4hep/k4FWCore#104]
As discussed in #100 `k4DataSvc` is effectively just a very thin wrapper around `PodioDataSvc` and can be removed. This issue is mainly for keeping track of the removal and for related discussions.

**Comment by jmcarcell** [comment]
`k4DataSvc` is used in many repos both in key4hep and other organizations so it's a fair amount of work for not much gain:
- https://github.com/search?q=org%3Akey4hep%20k4DataSvc&type=code
- https://github.com/search?q=org%3AHEP-FCC%20k4DataSvc&type=code
- https://github.com/search?q=org%3Acepc%20k4DataSvc&type=code
Alternatively we could move everything to `k4DataSvc` and remove `PodioDataSvc` since it's only used internally in this repo. I guess it makes sense if you're using key4hep that the name is `k4DataSvc`

**Comment by tmadlener** [comment]
There is another DataSvc `FCCDataSvc` that effectively does the same as `k4DataSvc`.

@kjvbrt @BrieucF is that still in use to the best of your knowledge?

**Comment by tmadlener** [comment]
There might be a technical reason for this split(?) At least simply merging `PodioDataSvc` into `k4DataSvc` and moving that to the core k4FWCore library, results in

```
[warning] library [k4FWCorePlugins] exposes factory [k4DataSvc] which is declared in [libk4FWCore.so] !!
```

and then subsequently runtime crashes with:
```
[k4run] : Configurable k4DataSvc not found in module k4FWCore.k4FWCorePluginsConf
Traceback (most recent call last):
  File "/home/tmadlener/work/key4hep/k4FWCore/k4FWCore/scripts/k4run", line 129, in <module>
    load_file(file)
  File "/home/tmadlener/work/key4hep/k4FWCore/k4FWCore/scripts/k4run", line 26, in load_file
    exec(file.read(), {})
  File "<string>", line 22, in <module>
TypeError: 'NoneType' object is not callable
```

**Comment by BrieucF** [comment]
> There is another DataSvc `FCCDataSvc` that effectively does the same as `k4DataSvc`.
> 
> @kjvbrt @BrieucF is that still in use to the best of your knowledge?

Hi Thomas, yes `FCCDataSvc` is used in some places outside of the Key4hep/HEP-FCC organizations but I can do the modification where I know it is used and advertise the change to the relevant mailing lists to warn people if it is decided to remove `FCCDataSvc`.

**Comment by kjvbrt** [comment]
We removed it some places, but not all, yet.

**Comment by tmadlener** [comment]
OK. Thanks for checking. We could put in some deprecation warning log message before completely removing it. That would at least make people aware if they are checking their logs.

**Comment by jmcarcell** [comment]
Since these services are going to be deprecated (see https://github.com/key4hep/k4FWCore/issues/292) this is not needed anymore.
